plugins {
    id 'fabric-loom' version '1.5-SNAPSHOT'
    id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = 'tpa-mod'
version = project.tpa_version
group = 'net.tpa'

repositories {
    maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.tpa_minecraft_version}"
    mappings "net.fabricmc:yarn:${project.tpa_minecraft_version}+build.10:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.tpa_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.tpa_fabric_api_version}"
}

processResources {
    inputs.property "version", project.tpa_version
    inputs.property "minecraft_version", project.tpa_minecraft_version
    inputs.property "loader_version", project.tpa_loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.tpa_version,
               "minecraft_version": project.tpa_minecraft_version,
               "loader_version": project.tpa_loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/repo"
        }
    }
}
